#!/usr/bin/env python
 
import subprocess
import json

def get_space(module):
    #space = []
    df = subprocess.Popen(["df", "-P", "-k",module.params['mountpoint']], stdout=subprocess.PIPE)
    #(rc,stdout,stderr)=module.run_command(df.communicate()[0])
    output = df.communicate()[0]
    for line in output.split("\n")[1:]:
        if len(line):
            try:
                device, size, used, available, percent, mountpoint = line.split()
                space=dict(mountpoint=mountpoint, used_percent=percent)
            except:
                pass
    module.exit_json(space=space, changed=False)            
    #print json.dumps({'space':space},indent=4)

def main():
    module=AnsibleModule(
            argument_spec=dict(
                mountpoint=dict(required=True),
            ),
            supports_check_mode=True
        )
    if module.check_mode:
        module.exit_json(changed=False)
    else:
        get_space(module)
            
from ansible.module_utils.basic import *

if __name__=='__main__':
    main()