#!/bin/bash
#mountpoint='/letv'
source $1
result=`df -P -k $mountpoint | tail -1`

read total used used_percent <<< `echo $result | awk '{print $2,$3,$5}'`

echo "{\"used_percent\":\"$used_percent\",\"total\":\"$total\",\"used\": \"$used\"}"

